# Generated by Django 5.1.15 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0098_prevadzka_gramage_summary_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Voliteľná HEX farba textu v gramážnej tabuľke a PDF. Keď je "
                    "nastavená spolu s background_color, použije sa presne táto "
                    "dvojica namiesto automaticky dopočítanej (#536)."
                ),
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="diet",
            name="background_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Voliteľná HEX farba podfarbenia riadku v gramážnej tabuľke a "
                    "PDF, viď text_color."
                ),
                max_length=7,
            ),
        ),
    ]
