# Generated by Django 5.1.15 on 2026-09-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0099_diet_text_and_background_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietComponentMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast_snack", "Raňajky-desiata"),
                            ("soup", "Polievka"),
                            ("main_course", "Hlavný chod"),
                            ("afternoon_snack", "Olovrant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component_index", models.PositiveSmallIntegerField()),
                (
                    "component_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_merges",
                        to="api.diet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "meal", "component_index"],
                "indexes": [
                    models.Index(
                        fields=["date", "meal"], name="api_dietcom_date_bee544_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "meal", "component_index", "diet"),
                        name="unique_diet_component_merge_slot",
                    )
                ],
            },
        ),
    ]
