# Generated by Django 5.1.15 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0099_diet_text_and_background_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryroute",
            name="vydaj",
            field=models.CharField(
                choices=[
                    ("A", "Cluster A"),
                    ("B", "Cluster B"),
                    ("C", "Cluster C"),
                    ("D", "Cluster D"),
                ],
                db_index=True,
                default="A",
                help_text=(
                    "Výdajný bod kuchyne, ktorý túto trasu obsluhuje. "
                    "Gramážová tabuľka sa delí podľa neho — trasy výdaja A "
                    "tvoria tabuľku A, trasy výdaja B tabuľku B, atď."
                ),
                max_length=1,
            ),
        ),
    ]
