# Generated by Django 5.1.15 on 2026-09-07

from decimal import Decimal, InvalidOperation

from django.db import migrations


def normalize_component_decimals(apps, schema_editor):
    MealTemplate = apps.get_model("api", "MealTemplate")
    changed = []
    for template in MealTemplate.objects.all().iterator():
        components = template.components or []
        normalized = []
        dirty = False
        for component in components:
            item = dict(component)
            grams = item.get("grams")
            if item.get("unit", "g") in {"g", "ml"} and grams not in (None, ""):
                text = str(grams).strip().replace(",", ".")
                try:
                    is_valid = Decimal(text).is_finite()
                except InvalidOperation:
                    is_valid = False
                if is_valid and text != grams:
                    item["grams"] = text
                    dirty = True
            normalized.append(item)
        if dirty:
            template.components = normalized
            changed.append(template)
    MealTemplate.objects.bulk_update(changed, ["components"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0100_add_cluster_d"),
    ]

    operations = [
        migrations.RunPython(normalize_component_decimals, migrations.RunPython.noop),
    ]
