# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0101_normalize_template_component_decimals"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="meal_day_restrictions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{jedlo: [ISO deň v týždni, 1=pondelok..7=nedeľa]} — obmedzenie, kedy sa dané jedlo (z visible_meals) dá objednať, napr. raňajky len v piatok = {"breakfast": [5]}. Chýbajúci kľúč alebo prázdny zoznam = každý deň.',
            ),
        ),
    ]
