# Generated by Django 5.1.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0103_dietcomponentmerge"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="maintenance_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Temporarily blocks client access during a scheduled update.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="maintenance_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="maintenance_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
