# Generated by Django 5.1.15 on 2026-09-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0104_globalsettings_maintenance_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyorder",
            name="attention_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="Admin odklikol 'attention' upozornenia z posledného scrapu ako vybavené pre tento konkrétny deň (Kontrola objednávok). Nedotýka sa config_notes/unmapped_diets/uncertain_diets — tie sa dajú vyriešiť len opravou dát. Scrape prepisuje `data`/`scrape_flags`, ale nie toto pole, takže dismiss v ten deň prežije aj ďalší hodinový beh; ďalší deň má vlastný DailyOrder riadok, takže sa flag prirodzene znova ukáže, ak pretrváva.",
            ),
        ),
    ]
