# Generated by Django 5.1.15 on 2026-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0105_dailyorder_attention_dismissed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyorder",
            name="attention_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="Admin odklikol VŠETKY upozornenia z posledného scrapu (attention/config_notes/unmapped_diets/uncertain_diets) ako vybavené pre tento konkrétny deň (Kontrola objednávok). Scrape prepisuje `data`/`scrape_flags`, ale nie toto pole, takže dismiss v ten deň prežije aj ďalší hodinový beh; ďalší deň má vlastný DailyOrder riadok, takže sa flag prirodzene znova ukáže, ak pretrváva — pre trvalé štrukturálne fakty (napr. škola nikdy nemá olovrant) oprav radšej PrevadzkaConfig/letter_hook priamo.",
            ),
        ),
    ]
