# Generated by Django 5.1.15 on 2026-09-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Merge dvoch nezávislých vetiev vzniknutých pri paralelnom vývoji
        # (#568 diet-component-merge a samostatné trasy per meal_type +
        # táto zmena) — obe vychádzali z 0102 a rozdelili sa na 0103_*.
        ("api", "0103_split_delivery_routes_by_meal_type"),
        ("api", "0106_alter_dailyorder_attention_dismissed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPackingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("pack_separately", models.BooleanField(default=False)),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.diet"
                    ),
                ),
            ],
            options={
                "unique_together": {("diet", "date")},
            },
        ),
    ]
